### ISSUE TITLE
Not able to modify roles of existed users

### ISSUE THREAD

**Issue by tdeng-pivotal** [pivotalservices/uaaldapimport#2]
I know this tool is for user builkimport. Is it possible to add features to modifying roles? As administrator may also need to modify existed users roles in batch.

**Comment by datianshi** [comment]
@tdeng-pivotal This tool's purpose is to associate the users with external user store (E.g. LDAP) with particular roles, while cross querying both uaa API (ldap) and cloud controller API (roles). Since modifying existing users roles not necessarily related to ldap/external user datastore, there is no UAA API involved. I am wondering this should be out of scopes. Users could simply batch modifying the roles through cf cli (talking against with cloud controller) with any bulk format representation.

**Comment by tdeng-pivotal** [comment]
@datianshi 
Thanks for your suggestion, cf cli is an good choice.
